name: "Run Checks"
on:
  workflow_dispatch: {}
  pull_request:
    branches:
    - main

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
          extra-platforms = aarch64-linux
    - run: |
        nix fmt .
        git diff-files --quiet || (git -P diff; echo -e "\nNOT FORMATTED: run 'nix fmt .'"; false)

  build_packages:
    needs: fmt
    strategy:
      matrix:
        package:
        - kernel_linux_6_6_rockchip.kernel
        - uBootRadxa-5-ITX
    runs-on: ubuntu-latest
    steps:
    - name: Free disk space
      run: |
        df -h
        sudo rm -rf /usr/share/dotnet /opt/ghc /usr/local/share/boost /usr/local/lib/android $AGENT_TOOLSDIRECTORY
        sudo docker image prune --all --force
        df -h
    - uses: actions/checkout@v4
    - run: |
        DEBIAN_FRONTEND=noninteractive
        sudo apt-get update -q -y && sudo apt-get install -q -y qemu-system-aarch64 qemu-efi binfmt-support qemu-user-static
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
          extra-platforms = aarch64-linux
    - run: |
        nix build -L -j4 .#${{ matrix.package }}

  build_example:
    needs: fmt
    runs-on: ubuntu-latest
    steps:
    - name: Free disk space
      run: |
        df -h
        sudo rm -rf /usr/share/dotnet /opt/ghc /usr/local/share/boost /usr/local/lib/android $AGENT_TOOLSDIRECTORY
        sudo docker image prune --all --force
        df -h
    - uses: actions/checkout@v4
    - run: |
        DEBIAN_FRONTEND=noninteractive
        sudo apt-get update -q -y && sudo apt-get install -q -y qemu-system-aarch64 qemu-efi binfmt-support qemu-user-static
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
          extra-platforms = aarch64-linux
    - working-directory: ./example
      run: |
        nix build -L -j4 --accept-flake-config --override-input rockchip ..
